name: S3 Updater

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: kersvers/s3-sync-with-cloudfront-invalidation@v1.0.0
        with:
          args: --follow-symlinks --delete --exclude '.git/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.S3BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.FAYZERPRODUCTIONACCESSKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FAYZERPRODUCTIONSECRETACCESSKEY }}
          DISTRIBUTION_ID: 'E34846GBV9BPSW'
          
