name: S3 Updater

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
      - uses: liftric/kirby-cloudfront-invalidations@master
        with:
          args: --follow-symlinks --delete --exclude '.git/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.S3BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.FAYZERPRODUCTIONACCESSKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FAYZERPRODUCTIONSECRETACCESSKEY }}
          
