name: Upload Website

on:
  push:
    branches:
    - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
      env:
        S3BUCKET: ${{ secrets.S3BUCKET }}
        GITHUBS3UPDATERKEY: ${{ secrets.GITHUBS3UPDATERKEY }}
        GITHUBS3UPDATERSECRETKEY: ${{ secrets.GITHUBS3UPDATERSECRETKEY }}
