name: Push to S3 Bucket

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.S3BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.GITHUBS3UPDATERKEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.GITHUBS3UPDATERSECRETKEY }}
